config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simpl#front_page'
  
  resources :players

  get '/sim_match' => 'simpl#sim_match'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  
    default_scope { order(created_at: :asc) }
    validates :zero_prob, :one_prob, :two_prob, :three_prob, :four_prob, :five_prob, :six_prob, :out_prob, presence: true, numericality: { only_integer: true }
    validate :sum_equals_100

    # Calling this function on a player instance returns a number between 0..7
    # 0..6 represent the runs scored. 7 represents OUT.
    # This is the weighted random number generation as per probabilities as asked in the question.
    def next_ball_result
      mapping = {"zero_prob": 0, "one_prob": 1, "two_prob": 2, "three_prob": 3, "four_prob": 4, "five_prob": 5, "six_prob": 6, "out_prob": 7}
      weighted = self.attributes.slice("zero_prob", "one_prob", "two_prob", "three_prob", "four_prob", "five_prob", "six_prob", "out_prob")
      max    = sum_of_weights(weighted)
      target = rand(1..max)
      weighted.each do |item, weight|
        return mapping[item.to_sym] if target <= weight
        target -= weight
      end
    end
    
    # Getting the sum of weights for weighted random number generation
    def sum_of_weights(weighted)
      weighted.inject(0) { |sum, (item, weight)| sum + weight }
    end

    def sum_equals_100
       if zero_prob + one_prob + two_prob + three_prob + four_prob + five_prob + six_prob + out_prob != 100
         errors.add(:base, 'Probabilities must sum to 100')
       end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:zero_prob, :one_prob, :two_prob, :three_prob, :four_prob, :five_prob, :six_prob, :out_prob)
    end
end

app/controllers/simpl_controller.rb
class SimplController < ApplicationController
  def front_page
    @players = Player.all
  end

  def sim_match
    @commentary = []
    
    # Initialize new match object
    @m = Match.new(40, 24)
    
    result = nil
    
    loop do
      @commentary << "#{(@m.balls_left / 6)} overs left. #{@m.score_left} runs to win." if @m.balls_left % 6 == 0
      current_player_name = Player.find(@m.current_strike_player_id).name

      # Simulate next ball
      next_ball = @m.next_ball
      next_comment = next_ball[1] == 7 ? "got Out" : "scored #{next_ball[1]} runs"
      @commentary << "#{current_player_name} #{next_comment}"
      
      if next_ball[0] != "Next"
        # Match Ends if result returned is not Next
        result = next_ball[0] # Save Winner
        break
      end
    end
    if result == "Bengaluru"
      # Bengaluru Winner Declaration Statement
      @result = "Bengaluru won by #{@m.next_player_ids.count + 1} wickets and #{@m.balls_left} balls remaining."
    elsif result == "Chennai"
      # Chennai Winner Declaration Statement
      @result = "Chennai won by #{@m.score_left} runs."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpl Engineering Test - Match Simulation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/players/_form.html.erb
<%= simple_form_for(@player) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :zero_prob %>
    <%= f.input :one_prob %>
    <%= f.input :two_prob %>
    <%= f.input :three_prob %>
    <%= f.input :four_prob %>
    <%= f.input :five_prob %>
    <%= f.input :six_prob %>
    <%= f.input :out_prob %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', root_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Zero prob</th>
      <th>One prob</th>
      <th>Two prob</th>
      <th>Three prob</th>
      <th>Four prob</th>
      <th>Five prob</th>
      <th>Six prob</th>
      <th>Out prob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.zero_prob %></td>
        <td><%= player.one_prob %></td>
        <td><%= player.two_prob %></td>
        <td><%= player.three_prob %></td>
        <td><%= player.four_prob %></td>
        <td><%= player.five_prob %></td>
        <td><%= player.six_prob %></td>
        <td><%= player.out_prob %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Zero prob:</strong>
  <%= @player.zero_prob %>
</p>

<p>
  <strong>One prob:</strong>
  <%= @player.one_prob %>
</p>

<p>
  <strong>Two prob:</strong>
  <%= @player.two_prob %>
</p>

<p>
  <strong>Three prob:</strong>
  <%= @player.three_prob %>
</p>

<p>
  <strong>Four prob:</strong>
  <%= @player.four_prob %>
</p>

<p>
  <strong>Five prob:</strong>
  <%= @player.five_prob %>
</p>

<p>
  <strong>Six prob:</strong>
  <%= @player.six_prob %>
</p>

<p>
  <strong>Out prob:</strong>
  <%= @player.out_prob %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', root_path %>

app/views/simpl/front_page.html.erb
<div class="row">
  <div class="col-md-12">
    <br>
    <h3>Bangalore vs Chennai</h3>
    <br>
    <h3>Match Simulation</h3>
    <br>
    <%= link_to "Simulate Match", sim_match_path, class: "btn btn-primary"  %>
    <br><br>

    <% @players.each do |player| %>
      <% @player = player %>
      <%= simple_form_for(@player, wrapper: :inline_form, html: { class: 'form-inline' }) do |f| %>

      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <h4><%= @player.name %></h4>
        <div class="form-inputs">
          <%= f.input :zero_prob, placeholder: "Zero Probability" %>
          <%= f.input :one_prob, placeholder: "One Probability" %>
          <%= f.input :two_prob, placeholder: "Two Probability" %>
          <%= f.input :three_prob, placeholder: "Three Probability" %>
          <%= f.input :four_prob, placeholder: "Four Probability" %>
          <%= f.input :five_prob, placeholder: "Five Probability" %>
          <%= f.input :six_prob, placeholder: "Six Probability" %>
          <%= f.input :out_prob, placeholder: "Out Probability" %>
          <%= f.button :submit %>
        </div>
        <br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/simpl/sim_match.html.erb
<div class="row">
  <div class="col-md-2">
    <br>
    <%= link_to "Go Back", root_path, class: "btn btn-primary" %>
  </div>
  <div class="col-md-8">
    <br>
    <h4><%= @result %><h4>
    <br>
    <h4>Score Card</h4>
    <br>
    <% @m.scorecard.each do |name, score| %>
      <% strike = @m.current_player_ids.include?(score[:id]) ? "*" : "" %>
      <text><%= "#{name} - #{score[:runs_scored]} #{strike} (#{score[:balls_played]} balls)" %></text>
      <br />
    <% end %>
    <br>
    <h4>Commentary</h4>
    <% @commentary.each_with_index do |comment, index| %>
      <% if index % 7 == 0 %>
        <br>
        <h6><%= comment %></h6>
      <% else %>
        <text class="small"><%= "#{index / 7}.#{index % 7} #{comment}" %></text>
        <br>
      <% end %>
    <% end %>
    <br>
    <h5>---- The End ----</h5>
    <br>
  </div>
</div>